<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://vuejs.org/api/sfc-script-setup.html#script-setup
import TComposition, { TCompositionProps } from './components/Templates/Composition'

// dummy data. likely computed together from API calls
// actions can be either functions passed in these top-level props, 
// or events generated by the top level component(s)
// whatever works, but consistency is key
const compositionProps: TCompositionProps = {
  navigationSide: {
    items: [
      {
        href: '#',
        text: 'Side item 1'
      },
      {
        href: '#',
        text: 'Side item 2'
      }
    ]
  },
  navigationTop: {
    items: [
      {
        href: '#',
        text: 'Top item 1'
      },
      {
        href: '#',
        text: 'Top item 2'
      }
    ]
  }
}
</script>

<template>
  <TComposition v-bind.prop="compositionProps" />
</template>